version: '3.8'

services:
  php:
    container_name: ai_audio_transcriber_php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - postgresql
      - redis

  nginx:
    container_name: ai_audio_transcriber_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .:/var/www
    depends_on:
      - php
      - postgresql

  postgresql:
    image: postgres:15-alpine
    container_name: ai-audio-transcriber-postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: ai-audio-transcriber-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
